name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Server Dependencies
        working-directory: ./server
        run: npm ci || npm install

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci || npm install

      - name: Build Client
        working-directory: ./client
        run: npm run build

      - name: Package Release
        run: |
          mkdir release_package
          cp -r server release_package/server
          cp -r client/dist release_package/client_dist
          zip -r release.zip release_package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
